name: Checks

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  tests:
    name: Checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Git version
        run: |
          git --version
      - name: Run check
        run: |
          make check
