name: Checks

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  tests:
    name: Checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: git version
        run: |
          git --version
      - name: git-config
        run: |
            git config --global user.email "kodapan@lithekod.se"
            git config --global user.name "Kodapan Apansson"
            git config --global init.defaultBranch "master"
      - name: Run check
        run: |
          make check
