name: Packaging

on:
  release:
      types: [published]

jobs:
  build:
    name: Package
    runs-on: ubuntu-latest
    steps:
      - name: install
        run: |
          sudo apt update  
          sudo apt install texlive-full

      - name: git-config
        run: |
          git config --global user.email "kodapan@lithekod.se"
          git config --global user.name "Kodapan Apansson"
          git config --global init.defaultBranch "master"

      - uses: actions/checkout@v2
        if: startsWith(github.ref, 'refs/tags/')

      - name: Package zip-file
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          make zip

      - name: Upload Release Asset
        uses: fnkr/github-action-ghr@v1
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GHR_PATH: ./git-in-git.zip
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
